### PR TITLE
Fix #41

### LINKED ISSUE #41: TypeError: Cannot read property 'split' of undefined
Running image actions on an existing repository, I received this error: 

```
/usr/local/src/image-actions/src/constants.js:15
const IGNORE_PATHS = process.env["INPUT_IGNOREPATHS"].split(",") || ["node_modules/**"];
                                                      ^

TypeError: Cannot read property 'split' of undefined
    at Object.<anonymous> (/usr/local/src/image-actions/src/constants.js:15:55)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/local/src/image-actions/entrypoint.js:3:45)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
##[error]Docker run failed with exit code 1
```

This is due to the change in #29

### PR DESCRIPTION
**Pull request by chabad360**
This PR should be able to fix #41.

### CODE REVIEW

**Comment by chabad360** [comment]
@benschwarz can you have a look?

**Comment by benschwarz** [comment]
Thanks @chabad360, but I think the current solution implemented yesterday is better. Parsing strings from YAML is not ideal and something that I'd avoided in image-actions when it was first written.

**Comment by chabad360** [comment]
> Parsing strings from YAML is not ideal

Isn't that what we do already tho? This is just a better, and cleaner way of doing it.
Also, I don't really see what's the issue with parsing strings...

**Comment by chabad360** [comment]
> Parsing strings from YAML is not ideal

@benschwarz Isn't that what we do already tho? This is just a better, and cleaner way of doing it (plus, it would seem that it's a [somewhat common](https://github.community/t5/GitHub-Actions/Can-action-inputs-be-arrays/m-p/33804/highlight/true#M1646) way of using arrays in GH Actions).
Also, I don't really see what's the issue with parsing strings...

**Pull request closed without merging**
