### PR TITLE
Allow for use in traditional CI builds.

### LINKED ISSUE #27: Compressing for builds
Is it possible to make this work for a build action? As I would find this very useful for things like static page blogs (that get built on GitHub Actions), where having compressed images is a plus, but not always is simple to compress images prior to committing, and this would be able to solve that issue...

### PR DESCRIPTION
**Pull request by chabad360**
This is a PR to fix #27. It would allow for using image-actions in a push-triggred workflow.

### CODE REVIEW

**Comment by benschwarz** [comment]
I know this is a work in progress but merging this would entirely break `image-actions`. 

The `Dockerfile` that you've removed is what builds the docker container in the first place. This is not mergeable in it's current state.

**Comment by chabad360** [comment]
your right, I was just trying to get it to build quickly while I was testing.

but other than that and the changes that are also present in my other
PR, is it still breaking?

On 11/25/19, Ben Schwarz <notifications@github.com> wrote:
> I know this is a work in progress but merging this would entirely break
> `image-actions`.
>
> The `Dockerfile` that you've removed is what builds the docker container in
> the first place. This is not mergeable in it's current state.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/calibreapp/image-actions/pull/30#issuecomment-558425899


-- 
Mendel G
chabad360@gmail.com

**Comment by chabad360** [comment]
Should no longer be breaking

**Comment by chabad360** [comment]
This is now able to be merged independently of #29.

**Comment by chabad360** [comment]
It seems that the action now no longer adds a comment regarding the compression info...

**Comment by chabad360** [comment]
> It seems that the action now no longer adds a comment regarding the compression info...

Just realized why: it's because the image isn't being optimized enough.

**Comment by chabad360** [comment]
@benschwarz can you have a look?

**Comment by benschwarz** [comment]
I will. Bit snowed under atm.

**Comment by chabad360** [comment]
I hate to be that guy, but just bumping this back to the notifications area...

**Comment by benschwarz** [comment]
@chabad360 Could you document what this code actually does? From what I can tell, it looks for either a pull request event, or a push. 

* **If it's a pull request event** - Commit the files, post the comment as usual.
* **If it's a push event** -- Process the images, don't commit anything, don't attempt to post a summary

How are you planning on using this? With GitHub? How would someone configure this? What would the workflow be?

**Comment by chabad360** [comment]
> How are you planning on using this? With GitHub? 

Yes.

> How would someone configure this?

Exactly the same way you do already.

> What would the workflow be?

Checkout [chabad360/chabad360.github.io](https://github.com/chabad360/chabad360.github.io), a single poster blog, adds image optimization to everything on build.

**Comment by kdeldycke** [comment]
I'd love to see that super-useful feature merged back upstream! 👍

**Comment by benschwarz** [comment]
This is now possible with `compressOnly` 👍

**Comment by kdeldycke** [comment]
Thanks @benschwarz. I was able to do what I was looking for at: https://github.com/kdeldycke/meta-package-manager/commit/6f86f616d07961ac76662ba5978f18205fc73176

**Comment by bazzadp** [comment]
Hey @kdeldycke

Just so you're aware, we made the compression report available in the `markdown` output variable even in `compressOnly` mode.

So one potential improvement would be this to add an `id` so you can add the results of the compression in your body using `{{ steps.calibre.outputs.markdown }}`

So something like this:

```yml
...
      - uses: calibreapp/image-actions@1.1.0
        id: calibre
...
          body: >
            [Auto-generated on run
            #${{ github.run_id }}](https://github.com/${{ github.repository
            }}/actions/runs/${{ github.run_id }}) as defined by [workflow
            action](https://github.com/${{ github.repository
            }}/blob/${{ github.base_ref }}/.github/workflows/autofix.yaml).%0A${{ steps.calibre.outputs.markdown }}
...
```

Note I'm using `%0A` as [an escaped newline](https://github.community/t/set-output-truncates-multiline-strings/16852) to give a break between your body and the report.

You can see [an example of this here](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1303).

**Comment by kdeldycke** [comment]
Oh. That's very nice! Thanks @bazzadp for the tip! 😃

**Pull request closed without merging**
