### PR TITLE
Fix: WebP Compression, support for .jpeg extensions and readme tidy

### LINKED ISSUE #46: image-action did not compress jpeg file
Just noticed today that the image-action seems not compressing the jpeg file (changing the file extension to jpg works for me)

/kind bug

### PR DESCRIPTION
**Pull request by benschwarz**
In this PR: 

### Bugs fixed
- [x] Added support for `.jpeg` file extensions (Closes #46)
- [x] Fixes broken WebP compression (#31)

### Other changes
- [x] Updates to the readme for legibility. Adds a table of contents for easier navigation.
- [x] Updates: ubuntu, libvips, adds many dependencies
- [x] Switches from node 11 to node 12 LTS

### CODE REVIEW

**Comment by benschwarz** [comment]
Closes #46

**Comment by benschwarz** [comment]
It looks like webps aren't currently being successfully read: 

`Input file contains unsupported image format` 

Confirms #31

**Comment by chenrui333** [comment]
@benschwarz can we break down this PR so that is easier to ship the functions? Thanks for fixing the issue!

**Comment by henrikemota** [comment]
Hello @benschwarz , have any updates on this bug?

**Comment by henrikemota** [comment]
Hello @benschwarz , have any updates on this bug?

**Pull request merged**
